### ISSUE TITLE
cors issues

### ISSUE THREAD

**Issue by yingwei1025** [luizjr92/stock-info#13]
Thanks for creating this, I try in Angular however I face the cors issues.  Been trying to resolve CORS errors by using Angular Proxy but still same

```
Access to XMLHttpRequest at 'https://query1.finance.yahoo.com/v7/finance/quote?symbols=GOOG' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by luiz-chagas** [comment]
Thanks!

Fixed on https://github.com/luiz-chagas/stock-info/commit/e7e7ea77df912d9006b67abeeab3a9f2102eb315
